#ifndef __dead
#define __dead	__attribute_((__noreturn__))
#endif

#ifndef SIMPLEQ_HEAD
#define SIMPLEQ_CONCAT		STAILQ_CONCAT
#define SIMPLEQ_EMPTY		STAILQ_EMPTY
#define SIMPLEQ_ENTRY		STAILQ_ENTRY
#define SIMPLEQ_FIRST		STAILQ_FIRST
#define SIMPLEQ_FOREACH		STAILQ_FOREACH
#define SIMPLEQ_FOREACH_SAFE	STAILQ_FOREACH_SAFE
#define SIMPLEQ_HEAD		STAILQ_HEAD
#define SIMPLEQ_HEAD_INITIALIZER	STAILQ_HEAD_INITIALIZER
#define SIMPLEQ_INIT		STAILQ_INIT
#define SIMPLEQ_INSERT		STAILQ_INSERT
#define SIMPLEQ_INSERT_AFTER	STAILQ_INSERT_AFTER
#define SIMPLEQ_INSERT_HEAD	STAILQ_INSERT_HEAD
#define SIMPLEQ_INSERT_TAIL	STAILQ_INSERT_TAIL
#define SIMPLEQ_LAST		STAILQ_LAST
#define SIMPLEQ_NEXT		STAILQ_NEXT
#define SIMPLEQ_REMOVE		STAILQ_REMOVE
#define SIMPLEQ_REMOVE_AFTER	STAILQ_REMOVE_AFTER
#define SIMPLEQ_REMOVE_HEAD	STAILQ_REMOVE_HEAD
#endif
