#ifndef __dead
#define __dead
#endif

#ifndef SIMPLEQ_CONCAT
#define SIMPLEQ_CONCAT		STAILQ_CONCAT
#endif

#ifndef SIMPLEQ_EMPTY
#define SIMPLEQ_EMPTY		STAILQ_EMPTY
#endif

#ifndef SIMPLEQ_ENTRY
#define SIMPLEQ_ENTRY		STAILQ_ENTRY
#endif

#ifndef SIMPLEQ_FIRST
#define SIMPLEQ_FIRST		STAILQ_FIRST
#endif

#ifndef SIMPLEQ_FOREACH
#define SIMPLEQ_FOREACH		STAILQ_FOREACH
#endif

#ifndef SIMPLEQ_FOREACH_SAFE
#define SIMPLEQ_FOREACH_SAFE	STAILQ_FOREACH_SAFE
#endif

#ifndef SIMPLEQ_HEAD
#define SIMPLEQ_HEAD		STAILQ_HEAD
#endif

#ifndef SIMPLEQ_HEAD_INITIALIZER
#define SIMPLEQ_HEAD_INITIALIZER	STAILQ_HEAD_INITIALIZER
#endif

#ifndef SIMPLEQ_INIT
#define SIMPLEQ_INIT		STAILQ_INIT
#endif

#ifndef SIMPLEQ_INSERT
#define SIMPLEQ_INSERT		STAILQ_INSERT
#endif

#ifndef SIMPLEQ_INSERT_AFTER
#define SIMPLEQ_INSERT_AFTER	STAILQ_INSERT_AFTER
#endif

#ifndef SIMPLEQ_INSERT_HEAD
#define SIMPLEQ_INSERT_HEAD	STAILQ_INSERT_HEAD
#endif

#ifndef SIMPLEQ_INSERT_TAIL
#define SIMPLEQ_INSERT_TAIL	STAILQ_INSERT_TAIL
#endif

#ifndef SIMPLEQ_LAST
#define SIMPLEQ_LAST		STAILQ_LAST
#endif

#ifndef SIMPLEQ_NEXT
#define SIMPLEQ_NEXT		STAILQ_NEXT
#endif

#ifndef SIMPLEQ_REMOVE
#define SIMPLEQ_REMOVE		STAILQ_REMOVE
#endif

#ifndef SIMPLEQ_REMOVE_AFTER
#define SIMPLEQ_REMOVE_AFTER	STAILQ_REMOVE_AFTER
#endif

#ifndef SIMPLEQ_REMOVE_HEAD
#define SIMPLEQ_REMOVE_HEAD	STAILQ_REMOVE_HEAD
#endif
