.\"     $OpenBSD$
.\"
.\" Copyright (c) 2020 Vadim Zhukov <zhuk@openbsd.org>
.\"
.\" Permission to use, copy, modify, and distribute this software for any
.\" purpose with or without fee is hereby granted, provided that the above
.\" copyright notice and this permission notice appear in all copies.
.\"
.\" THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
.\" WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
.\" MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
.\" ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
.\" WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
.\" ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
.\" OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
.Dd $Mdocdate$
.Dt OICB 1
.Os
.Sh NAME
.Nm oicb
.Nd command-line ICB client
.Sh SYNOPSIS
.Nm oicb
.Op Fl dH
.Op Fl t Ar secs
.Oo Ar nick@ Oc Ns Ar host Ns Oo Ar :port Oc
.Ar room
.Sh DESCRIPTION
The
.Nm
is a minimalistic command-line ICB client.
The options are as follows:
.Bl -tag -width Ds
.It Fl d
Debug mode: enables printing some internal state information.
If this flag is specified more than once, more stuff will be printed.
Also, the
.Ic Ctrl+X
key combination is reserved in debug mode for developer needs.
.It Fl H
Disable local chat history saving (see below).
.It Fl t Ar secs
Set server timeout value to
.Ar secs .
The default is 30 (seconds).
.It Ar nick
Nickname to use on server.
By default user's login name is used, as returned by
.Xr getlogin 2 .
.It Ar host
The ICB server host name or address.
IPv6 addresses must be enclosed in square brackets, to disambiguate
with port specification.
.It Ar port
The ICB server TCP port to use, defaulting to 7326.
.It Ar room
Name of the room to enter upon login.
.El
.Pp
Up to 5 last nick names used for sending private messages during current
login session are remembered.
.Sh CHAT HISTORY
By default,
.Nm
saves chat history to
.Pa ~/.oicb/logs/ Ns Ar host
directory.
Chatroom logs are prefixed with
.Sq room-
and private chats are prefixed with
.Sq private- .
.Sh KEY BINDINGS
.Bl -tag -width "Shift+TAB" -compact
.It Ic TAB
Select next private chat.
.It Ic Shift+TAB
Select previous private chat.
.It Ic ^P
Display current private chat names history.
.It Ic ^T
Display information about current chatroom and user.
.El
.Sh SEE ALSO
Other ICB implementations:
.Lk http://www.icb.net/ .
.Pp
The ICB protocol description:
.Lk ftp://ftp.icb.net/pub/icb/src/icbd/Protocol.html
.Sh AUTHORS
.An Vadim Zhukov Aq Mt zhuk@openbsd.org
