#!/bin/ksh

. ${0%/*}/common.ksh

run_icbd

ICB_RUN_NUM=1
run_oicb user1 roomfoo <<EOE &
expect "You are now in group roomfoo" { send "/m user1 test 1 to 1\n" }
expect {
	"user2 * entered group"	{ sleep 1; send "ICQ\n" }
	"> ICQ"
}
send "/m user2 test 1 to 2"
expect "] \\*user2\\* test 2 to 1"	{ send "test 3\t" }
expect "/m user2 test 3"		{ send "a\t" }
expect "/m user1 test 3a"		{ send "b\t" }
expect "test 3ab"			{ exit 0 }
exit 1
EOE

sleep 1

ICB_RUN_NUM=2
run_oicb user2 roomfoo <<EOE &
expect "You are now in group roomfoo" { send "/m user2 test 2 to 2\n" }
expect {
	"user1 * entered group" { sleep 1; send "ICQ\n" }
	"> ICQ"
}
expect "] \\*user1\\* test 1 to 2" {
	send "/m user1 test 2 to 1\n"
}
expect "\\[=Sign-off=] user2 (user2@127.0.0.1) just left" { exit 0 }
exit 1
EOE
