name: FreeBSD-based build

on: [push]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - name: checkout
      uses: actions/checkout@v2

    - name: build in FreeBSD
      uses: vmactions/freebsd-vm@v0.1.4
      with:
        usesh: true
        prepare: pkg install -y cmake readline
        run: |
          mkdir build
          cd build
          cmake --trace-redirect=CMakeTrace.log -DCMAKE_BUILD_TYPE=Release ..
          make VERBOSE=1

    - name: archive error logs
      if:   failure()
      uses: actions/upload-artifact@v2
      with:
        name: freebsd-build-logs
        path: build/**/*.log
