name: latest Ubuntu-based build

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: install dependencies
      run: sudo apt-get install libncurses-dev libreadline-dev
    - name: create build directory
      run: mkdir build
    - name: configure
      run: cmake ..
      working-directory: build
    - name: make
      run: make
      working-directory: build
